<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<?codewarrior exportversion="1.0" ideversion="5.0" ?>

<!DOCTYPE EXPORTEDPANEL [
<!ELEMENT EXPORTEDPANEL (NAME, (SETTINGLIST|VALUE))>
<!ELEMENT SETTINGLIST (SETTING+)>
<!ELEMENT SETTING (NAME?, (VALUE|(SETTING+)))>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT VALUE (#PCDATA)>
]>

<EXPORTEDPANEL>
    <NAME>Access Paths</NAME>
    <SETTINGLIST>
        <SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>false</VALUE></SETTING>
        <SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>false</VALUE></SETTING>
        <SETTING><NAME>RequireFrameworkStyleIncludes</NAME><VALUE>false</VALUE></SETTING>
        <SETTING><NAME>UserSearchPaths</NAME>
            <SETTING>
                <SETTING><NAME>SearchPath</NAME>
                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
            </SETTING>
        </SETTING>
        <SETTING><NAME>SystemSearchPaths</NAME>
            <SETTING>
                <SETTING><NAME>SearchPath</NAME>
                    <SETTING><NAME>Path</NAME><VALUE>CW for Palm OS Support\(ARMlet Support)</VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
            </SETTING>
            <SETTING>
                <SETTING><NAME>SearchPath</NAME>
                    <SETTING><NAME>Path</NAME><VALUE>Palm OS Support</VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
            </SETTING>
            <SETTING>
                <SETTING><NAME>SearchPath</NAME>
                    <SETTING><NAME>Path</NAME><VALUE>CW for Palm OS Support</VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
            </SETTING>
        </SETTING>
    </SETTINGLIST>
</EXPORTEDPANEL>
